### ISSUE TITLE
ngrx-slice How to create custom selectors for ngrx-slice generated state

### ISSUE THREAD

**Issue by fatihdogmus** [nartc/nartc-workspace#1]
Hello Chau,

We've been using ngrx-slice for a while and it is super useful.

I bumped into an issue where I need to transform a portion of the state and select that. I've looked at documentation, but couldn't find anything on how to add a custom selector to my slice. I tried using createSelector from ngrx, but I couldn't get it working. Can you give me some tips?

Thank you for your help.

**Comment by nartc** [comment]
Thank you for the kind words. Have you looked at this https://github.com/nartc/todomvc-ngrx-slice/blob/slice/src/app/todo/store/slice.ts ? I know it's "entity" but the way you use createSelector would be the same.

**Comment by fatihdogmus** [comment]
Thank you very much, that is exactly what I needed! Cheers for fast reply and help!
