### ISSUE TITLE
[ngrx-slice] depend on Angular 14 packages

### ISSUE THREAD

**Issue by dJani97** [nartc/nartc-workspace#3]
Hey!
First of all, thank you for this awesome package, it really makes development a lot faster.

I have tried upgrading a project to Angular 14 that uses slice, but I get the following error:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: my-frontend-package@0.0.0
npm ERR! Found: @angular/common@14.0.5
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^14.0.5" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^13.0.0" from ngrx-slice@6.2.1
npm ERR! node_modules/ngrx-slice
npm ERR!   ngrx-slice@"^6.2.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

Peer dependencies like ngrx-immer [seem to be compatible with Angular 14](https://github.com/timdeschryver/ngrx-immer/issues/16). Could you please update the ngrx-slice package?

The project does work well with the `--legacy-peer-deps` option though, so I hope upgrading won't mean too much refactoring.

**Comment by nartc** [comment]
@dJani97 Thank you for the kind words. I've just released 6.3.0 which bumps the version of Angular and NgRx to 14.

**Comment by dJani97** [comment]
Thank you for the quick release!

I suggest adding v14 compatibility to the [docs > peer-dependencies](https://ngrx-slice.netlify.app/#peer-dependencies) section, like so:

<html>
<body>


NgRx Slice | Angular | NgRX
-- | -- | --
v6.3 and above | v14 | v14
v6 - v6.2 | v13 | v13
v5 | v11, v12 | v11, v12
No support for Angular <11 because of TypeScript version


</body>
</html>

**Comment by nartc** [comment]
Yep, I can push a commit for docs later. I always forget updating docs xD
