### ISSUE TITLE
How do we pass payload to reducer?

### ISSUE THREAD

**Issue by Tzvetelin88** [nartc/nartc-workspace#6]
Hello, first want to thanks so much for this lib! - faster and easier way do to stuff as we have it in Redux and Redux Toolkit.
Do we pass payload as the same way we do in React/Redux, where each reducer have state and action?

```
export const {
  actions: CounterActions,
  selectors: CounterSelectors,
  ...CounterFeature
} = createSlice({
  name: "authReducer",
  initialState,
  reducers: {
    login: (state, action) => {
      const user = new User(
        action.email,
        action.userId,
        action.token,
        action.expirationDate
      );

      state.authError = null;
      state.user = user;
      state.loading = false;
    },
    logout: (state) => {
      state.user = null;
    },
  },
});
``

**Comment by nartc** [comment]
Thank you for the kind words. The `action` should contain the payload but you need to annotate the `action` type explicitly with `PayloadAction<TheTypeGoesHere>` then you'd be able to access it in the reducer.

```ts
interface User {
    firstName: string;
    lastName: string;
}

export const {...} = createSlice({
    name: 'authReducer',
    initialState,
    reducers: {
        login: (state, action: PayloadAction<User>) {
             // action.firstName, action.lastName etc...
        }
    }
})
```

**Comment by Tzvetelin88** [comment]
Thanks so much for the info, I will re-work some stuff this week, and I hope everything goes well.
